import { CapstoneProject } from '@/types/curriculum';

export const SQL_CAPSTONE_PROJECT: CapstoneProject = {
  id: 'project_ecommerce_analytics',
  nodeId: 'node_capstone_project',
  title: 'Global Retail Intelligence Capstone',
  company: 'NovaTech Omnichannel Enterprises',
  role: 'Senior Analytics Engineer',
  mission: 'Deliver a comprehensive end-to-end SQL reporting suite analyzing product line profitability, customer lifetime value (LTV), cross-department basket size, and channel sales velocity.',
  datasetOverview: 'Access full relational schemas: customers, categories, products, orders, order_items, payments, and subscriptions.',
  rewardTitle: 'Certified SQL Architect',
  xpReward: 300,
  tasks: [
    {
      id: 'task_1',
      taskNumber: 1,
      title: 'Department Revenue Contribution',
      question: 'Calculate total revenue generated by each product department. Select categories.department, COUNT(DISTINCT orders.order_id) AS total_orders, and ROUND(SUM(order_items.quantity * order_items.unit_price), 2) AS department_revenue. Group by department and sort from highest revenue to lowest.',
      businessObjective: 'Analyze which core business unit (Computing, Workplace, Enterprise, Consumer) drives the highest gross product sales.',
      expectedQuery: 'SELECT c.department, COUNT(DISTINCT o.order_id) AS total_orders, ROUND(SUM(oi.quantity * oi.unit_price), 2) AS department_revenue FROM categories c INNER JOIN products p ON c.category_id = p.category_id INNER JOIN order_items oi ON p.product_id = oi.product_id INNER JOIN orders o ON oi.order_id = o.order_id GROUP BY c.department ORDER BY department_revenue DESC;',
      hints: [
        'Join categories -> products -> order_items -> orders.',
        'Use SUM(oi.quantity * oi.unit_price) for actual line item revenue.',
        'Group by c.department and order by department_revenue DESC.'
      ],
      explanation: 'Multi-table star schema join correctly attributed revenue across departmental hierarchies.',
      xp: 50
    },
    {
      id: 'task_2',
      taskNumber: 2,
      title: 'Product Velocity & Stock Depletion Risk',
      question: 'Identify top-selling products by quantity ordered. Select products.product_id, products.name, products.stock_quantity, and SUM(order_items.quantity) AS total_units_sold. Group by product and order by total_units_sold DESC LIMIT 4.',
      businessObjective: 'Prevent stockouts for high-velocity SKUs before peak seasonal demand.',
      expectedQuery: 'SELECT p.product_id, p.name, p.stock_quantity, SUM(oi.quantity) AS total_units_sold FROM products p INNER JOIN order_items oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.name, p.stock_quantity ORDER BY total_units_sold DESC LIMIT 4;',
      hints: [
        'Join products and order_items on product_id.',
        'Group by p.product_id, p.name, p.stock_quantity.',
        'Order by total_units_sold DESC LIMIT 4.'
      ],
      explanation: 'Identified top SKU turnover rates for automated inventory replenishment triggers.',
      xp: 60
    },
    {
      id: 'task_3',
      taskNumber: 3,
      title: 'Customer Lifetime Value (LTV) Segmentation',
      question: 'Use a CTE to classify customers based on their historical spend. Create a CTE customer_spend with customer_id and total_spent = SUM(total_amount) from orders. In the outer query, select customer_id, total_spent, and a CASE expression: "VIP" if total_spent >= 2500, "Loyal" if total_spent >= 1000, else "Standard" aliased as ltv_tier. Order by total_spent DESC.',
      businessObjective: 'Empower customer success teams to tailor white-glove incentives to high-LTV accounts.',
      expectedQuery: "WITH customer_spend AS (SELECT customer_id, SUM(total_amount) AS total_spent FROM orders GROUP BY customer_id) SELECT customer_id, total_spent, CASE WHEN total_spent >= 2500 THEN 'VIP' WHEN total_spent >= 1000 THEN 'Loyal' ELSE 'Standard' END AS ltv_tier FROM customer_spend ORDER BY total_spent DESC;",
      hints: [
        'Define WITH customer_spend AS (SELECT customer_id, SUM(total_amount) AS total_spent FROM orders GROUP BY customer_id).',
        'In the outer query, apply CASE WHEN ... THEN ... ELSE ... END AS ltv_tier.',
        'Sort by total_spent DESC.'
      ],
      explanation: 'Engineered clean customer LTV tiers ready for ingestion by marketing automation tools.',
      xp: 65
    },
    {
      id: 'task_4',
      taskNumber: 4,
      title: 'Preferred Payment Rails Distribution',
      question: 'Calculate the total processed volume and transaction share for each payment method among approved payments. Select payment_method, COUNT(*) AS transactions, SUM(amount) AS total_volume FROM payments WHERE status = \'approved\' GROUP BY payment_method ORDER BY total_volume DESC;',
      businessObjective: 'Audit merchant interchange fee exposure across credit card, PayPal, and Apple Pay rails.',
      expectedQuery: "SELECT payment_method, COUNT(*) AS transactions, SUM(amount) AS total_volume FROM payments WHERE status = 'approved' GROUP BY payment_method ORDER BY total_volume DESC;",
      hints: [
        "Filter for status = 'approved'.",
        'Group by payment_method.',
        'Order by total_volume DESC.'
      ],
      explanation: 'Dissected financial transaction settlement efficiency across payment gateways.',
      xp: 60
    },
    {
      id: 'task_5',
      taskNumber: 5,
      title: 'Monthly Order Revenue Trajectory',
      question: 'Analyze gross sales trajectory across calendar months. Use SUBSTR(order_date, 1, 7) AS order_month from orders. Select SUBSTR(order_date, 1, 7) AS order_month, COUNT(*) AS monthly_orders, SUM(total_amount) AS monthly_revenue FROM orders GROUP BY order_month ORDER BY order_month ASC;',
      businessObjective: 'Produce monthly run-rate trajectory charts for the executive quarterly board review.',
      expectedQuery: 'SELECT SUBSTR(order_date, 1, 7) AS order_month, COUNT(*) AS monthly_orders, SUM(total_amount) AS monthly_revenue FROM orders GROUP BY order_month ORDER BY order_month ASC;',
      hints: [
        'SUBSTR(order_date, 1, 7) extracts YYYY-MM.',
        'Group by order_month and order by order_month ASC.'
      ],
      explanation: 'Capstone Completed! You successfully constructed a professional retail analytics intelligence model from scratch.',
      xp: 65
    }
  ]
};
